### ISSUE TITLE
[Feature] [VDP] [Pipelines] Workflow automation

### ISSUE THREAD

**Issue by chuang8511** [instill-ai/instill-core#1022]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where do you intend to apply this feature?

Instill Core, Instill Cloud

### Is your Proposal Related to a Problem?

# Background

There are lots of project management tools now, and the internal information is scattered around in those tools.

### Describe Your Proposed Solution

# User stories

## Story 1

As a project manager, he/she wants to align all information in all platform with correct format when a information is sync in one tool.

Possible pipelines
![image](https://github.com/instill-ai/instill-core/assets/64747455/301d540c-a5ad-450c-b94d-ab5cd8d9773e)

Concrete example
![image](https://github.com/instill-ai/instill-core/assets/64747455/2b37efe9-890c-4b2c-a22e-3848f232c6cb)

### Highlight the Benefits

It can solve the problem in the real world.

### Anything Else?

# Possible components
- Note: The sequence means the priority.

# Application components
- GitHub
- Jira
- Trello
- Asana
- Linear
- …

# Reference tools
- I have not found the close product. We could imagine that the tools have been integrated AI solutions internally, such as Asana / Notion / Gmail /…
- But, they do not have the process to sync the information to other ApplicationSource.
  - e.g. Asana information -> AI tools -> Linear / Slack / Gmail /…

# Milestones

1. Read the current pipelines
  - https://instill.tech/abrc/pipelines/stomavision
  - https://instill.tech/pinglin/pipelines/contract-reviewer
  - https://instill.tech/gstrong/pipelines/quickstart
2. Design the pipeline according to user stories.
  - Please draw the concrete pipelines first to ask us review before delving into development.
  - Timeline: 5 working days
3. Check which components we are missing according to the designed pipeline.
  - Please create the skeleton PR first for the incoming components
  - Timeline: 2~3 working days
4. Connect those components.
  - Timeline: 10 working days
5. Build the designed pipeline after you connect those components.
  - Timeline: 1 working day

## Note
- About timeline, let's adjust it dynamically if there are much more complicated issues than we think
- Milestone 2~5 is a cycle. Let's finish a whole complete user story first and then iterate it.

**Comment by YCK1130** [comment]
Hi @chuang8511 ! As shown in the following figure, I plan to construct a pipeline to assist the code review process.
<img width="689" alt="Screenshot 2024-06-24 at 2 16 25 PM" src="https://github.com/instill-ai/instill-core/assets/85488391/99e0b07f-d32b-4f85-af33-4a1cff2a3840">
I would appreciate any feedback!

# TODO - Add a GitHub component
## Must
- [ ] read a pull request data
- [ ] read commit messages
- [ ] comment under a pull request
- [ ] register webhook
## Additional
- [ ] Post issue
- [ ] Create pull request
- [ ] Edit pull request
- [ ] Edit issue

**Comment by chuang8511** [comment]
Hi @YCK1130 cc'd  mentor(@xiaofei-du )  Project Lead (@donch1989 )
Thanks for providing this clear image.

There are a few things we need to do and check before delving into development.
1. TODO: I forgot to add the user story about your GitHub story. Could you help me write it in this ticket or your sub-ticket?
  - e.g. As a engineer manager, he/she wants to ....

2. Feedback: I am not a proficient in this domain, but, in my opinion, current design looks similar with lint function such as golintci.
  - I guess we need to input more data rather than only PR information. When I review others' code, I also read the code that is not in the PR files. So, it means LLM model probably requires those information to provide a good result.


3. Feedback: Previously, I had to review others' code. Usually, I only review function code rather than test code. I think it would be good that there is a system to help me review the quality of test code.
  - e.g. test coverage / mock strategy / ...

Please feel free to comment back if there is anything unclear.
