### ISSUE TITLE
[Feature] [VDP] [Components] Connects AI vendors

### ISSUE THREAD

**Issue by chuang8511** [instill-ai/instill-core#1024]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Where do you intend to apply this feature?

Instill Core, Instill Cloud

### Is your Proposal Related to a Problem?

# Background

We want users to have more optional models to be used

### Describe Your Proposed Solution

# User Stories
- As a user, they can easily trigger a pipeline to use a model in the popular vendors.

### Highlight the Benefits

The users can use more and more models in VDP

### Anything Else?

# Planned Components
- Anthropic
  - [ref](https://python.langchain.com/v0.2/docs/integrations/platforms/anthropic/)
- Cohere
  - [ref](https://python.langchain.com/v0.2/docs/integrations/providers/cohere/)
- Mistral
  - [ref](https://python.langchain.com/v0.2/docs/integrations/providers/mistralai/)
- Google
  - [ref](https://python.langchain.com/v0.2/docs/integrations/platforms/google/)
- AWS
  - [ref](https://python.langchain.com/v0.2/docs/integrations/platforms/aws/)
- Microsoft
  - [ref](https://python.langchain.com/v0.2/docs/integrations/platforms/microsoft/)

# Milestones
1. Please create the skeleton PR first for the incoming components
2. Connect those components.
3. Build the designed pipeline after you connect those components.

**Comment by namwoam** [comment]
We can differentiate the AI vendors into the following three category:
PaaS (Platform as a service) Providers, which requires complex IAM authentication, project permission settings.
1. [ ] GCP (Google)
2. [ ] AWS (Amazon)
3. [ ] Azure (Microsoft)
4. [ ] Watsonx (IBM)
MaaS (Model as a service) Providers, which often use simple API keys
 1. [x] OpenAI
 2. [x] Anthropic
 3. [x] Cohere
 4. [x] Mistral AI
 5. [ ] Fireworks AI [link](https://fireworks.ai/)
 6. [ ] AI21 labs [link](https://www.ai21.com/)
 7. [ ] Upstage [link](https://developers.upstage.ai/)
 8. [ ] Voyage AI [link](https://www.voyageai.com/)
 9. [ ] Deep infra[link](https://deepinfra.com/)
 10. [ ] Deepgram [link](https://deepgram.com/)
 11. [ ]  unstructured [link](https://unstructured.io/blog)
 12. [ ]  jina.ai [link](https://jina.ai/)
 13. [ ]  bria.ai [link](https://bria.ai/)
 SaaS (Software as a service), which often could only be accessed via GUI, thus impossible to integrate into VDP
 example: OpenArt [link](https://openart.ai/home)
