### ISSUE TITLE
Tasks for releasing the VDP project

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/instill-core#887]
## Summery
Here we collect a list of tasks that needs to be completed to release the VDP project

#### Quick start example
- [x] instill-ai/instill-core#882

#### Improve Documentation
- How VDP works
  - [x] instill-ai/vdp#52
  - [x] instill-ai/instill-core#885
  - [x] instill-ai/instill-core#884
- Quick start
  - [x] instill-ai/instill-core#883

### Protobufs
- [x] https://github.com/instill-ai/protobufs/issues/8

### Protogen-go
- [x] https://github.com/instill-ai/protogen-go/issues/20
